name       : pelican
version    : 4.2.0
release    : 6
source     :
    - https://github.com/getpelican/pelican/archive/4.2.0.tar.gz : 4b0d4c9439217b49ace89f4f8b52c90e13fa283a786d7b12e2020a11f32f9a33
license    : AGPL-3.0-only
component  : programming
summary    : Static site generator that supports Markdown and reST syntax. Powered
    by Python
description: |
    Pelican is a static site generator written in Python.
    It uses Markdown and reStrcturedText for writing content, inclues a simple command line tool to (re)generate site files.
builddeps  :
    - python-sphinx
rundeps    :
    - pygments
    - python-blinker
    - python-dateutil
    - python-docutils
    - python-feedgenerator
    - python-jinja
    - python-markdown
    - python-pytz
    - python-six
    - python-unidecode
setup      : |
    sed -i 's|etc/bash_completion.d|share/bash-completion/completions|' setup.py
    sed -i 's|etc/fish/completions|share/fish/completions|' setup.py
    %python3_setup
install    : |
    %python3_install
